### ISSUE TITLE
[EPIC] Referral Program

### ISSUE THREAD

**Issue by r0wdy1** [zkBob/rewards_rervice#1]
# What to do? 

We need to implement the mechanic for the zkBob referral program

**The mechanic of the referral program:**
We will split between referral and referee difference that the relayer actually spends for a transfer inside the pool with a fixed relayer fee (0.1 BOB)

Main mechanic and user flow you can find here - https://www.notion.so/blockscout/Referral-program-7af5b0c4d84e42608204041bad85162d

@r0wdy1 Could you please decompose this task before planning?

**UPD 19.01:**
Decomposition could be found here 👇
https://www.notion.so/blockscout/Referral-program-7af5b0c4d84e42608204041bad85162d#530fd3c7fa9b4eb7b36e69b5dce6a05f

## The flow:

1. The Referrer generates a link with a ref_code query parameter and shares it with Referee(s).
2. The Referee gets a link somewhere and gets through onboarding process. Ref_code is automatically saved when account setup happens
3.  The Referee makes a transfer, the ref code is appended to the transaction memo
4. At the end of reporting period, all of the transactions are grouped by ref_code and rewards are calculated and automatically sent to the Refferer ZK address

- [ ] UI: zkBob/zkbob-ui#131
- [ ] UI: zkBob/zkbob-ui#132
- [ ] libzkbob-rs: zkBob/libzkbob-rs/issues/44
- [ ] clientjs-lib: zkBob/zkbob-client-js/issues/90

**Comment by 0xdeval** [comment]
Better to do with https://github.com/zkBob/zkbob-client-js/issues/40

**Comment by 0xdeval** [comment]
Conclusion from the tech call 03.03:
1. We  can implement the referral program where we will split the positive residual between a referral and referee
2. The current amount of fees that we took from users is not enough to motivate our users. Just an example: if we had 1 user who invited another 14000 users (all users that we have right now in zkBob) using the referral program, he got about 100$ from the whole time. The positive residual us mostly too low to be profitable for a user 
3. We need to find new channels to monetize the product. If we would add new channels we could offer users more interesting offers
